### PR TITLE
just made a new animation called stop-rain

### PR DESCRIPTION
**Pull request by aditya1rawat**

### CODE REVIEW

**Comment by calixo888** [comment]
Awesome, thanks @aditya1rawat! I'll take a look at this soon :)

**Comment by aditya1rawat** [comment]
Awesome Thanks!

**Comment by calixo888** [comment]
Hey @aditya1rawat, did you build this in HTML5 Canvas or something called Sketch?

All of our animations use HTML5 Canvas so it's easier to integrate into certain containers, making it easier to copy-paste code and let each animations stay within it's own container.

**Comment by aditya1rawat** [comment]
Yeah I used Sketch. If you need me to change it lmk.

**Comment by calixo888** [comment]
Yeah, if you could try to change it to HTML5 Canvas, just because that's what's most compatible with Ano.js. Thanks!

**Pull request closed without merging**
